### ISSUE TITLE
Update GameLog triggers to NpcYell/BattleTalk2

### ISSUE THREAD

**Issue by wexxlee** [OverlayPlugin/cactbot#84]
### Feature(s) Requested

A quick search shows the following timelines & triggers are using `GameLog` (0x00) lines.  At least some of these can be replaced by the new `NpcYell` and `BattleTalk2` lines now available through OverlayPlugin (I haven't reviewed these to confirm which; this is more of a potential candidate list):

Timelines:

- [X] 02-arr/trial/ifrit-nm.txt (#90)
- [X] 03-hw/dungeon/gubal_library_hard.txt (#95)
- [X] 04-sb/alliance/orbonne_monastery.txt (#99)
- [X] 04-sb/alliance/royal_city_of_rabanastre.txt (☝️)
- [X] 04-sb/dungeon/fractal_continuum_hard.txt (☝️)
- [X] 04-sb/raid/o9n.txt (☝️)
- [X] 04-sb/raid/o11n.txt (☝️)
- [X] 04-sb/raid/o12n.txt (☝️)
- [X] 04-sb/raid/o12s.txt (☝️)
- [X] 05-shb/eureka/delubrum_reginae_savage.txt (#101)
- [X] 05-shb/trial/hades-ex.txt (☝️)
- [X] 06-ew/trial/endsinger.txt (#102)

Triggers:

- [X] 02-arr/dungeon/haukke_manor.ts (#90)
- [X] 02-arr/raid/t8.ts (☝️)
- [X] 03-hw/alliance/dun_scaith.ts (#95)
- [X] 03-hw/pvp/shatter.ts (☝️)
- [X] 03-hw/raid/a11s.ts (☝️)
- [X] 04-sb/eureka/eureka_anemos.ts (#99 - but see comments)
- [X] 04-sb/eureka/eureka_hydatos.ts (☝️)
- [X] 04-sb/eureka/eureka_pagos.ts (☝️)
- [X] 04-sb/eureka/eureka_pyros.ts (☝️)
- [X] 04-sb/trial/byakko-ex.ts (☝️)
- [X] 04-sb/trial/tsukuyomi-ex.ts (☝️)
- [X] 04-sb/ultimate/unending_coil_ultimate.ts (#83)
- [X] 05-shb/alliance/the_copied_factory.ts (#101)
- [X] 05-shb/etc/the_diadem.ts (☝️)
- [X] 05-shb/eureka/bozjan_southern_front.ts (☝️)
- [X] 05-shb/eureka/zadnor.ts (☝️)

If anyone has time to start working through these (even if to confirm they don't need updates), feel free to edit this post and tag whichever ones you intend to work on, or reply below!

**Comment by wexxlee** [comment]
The above list is done, but there are TODOs in the below files with triggers/timeline entries that should be updated when OverlayPlugin/OverlayPlugin#329 lands, so going to leave this open for now to track the follow up work:
- [ ] 04-sb/eureka/eureka_hydatos.ts
- [ ] 05-shb/eureka/bozjan_southern_front.ts
- [ ] 05-shb/eureka/delubrum_reginae_savage.txt
